create table users (
    id              integer         primary key generated by default as identity (start with 45),
    login           varchar(30),
    password        varchar(30),
    role            varchar(15),
    active          boolean,
    name            varchar(30),
    surname         varchar(30),
    patronymic      varchar(30),
    tg_id           bigint,
    subgroup        varchar(30),
    trust           boolean
);

-- role admin, worker

insert into users values(1, 'admin@ultradop.online', 'test', 'admin', 't', 'Сергей');
insert into users values(2, 'superWorker@ultradop.online', 'test', 'worker', 't');
insert into users values(3, 't@t.t', 'test', 'admin', 't', 'год');

create table points (
    id              integer         primary key generated by default as identity (start with 8000),
    active          boolean,
    long            float8,
    lat             float8,
    address         varchar(150),
    district        varchar(100),
    number_arc      integer,
    arc_type        varchar(30),
    carpet          varchar(30),
    change_date     timestamp,
    comment         varchar(500),
    status          varchar(100),
    owner           varchar(100),
    operator        varchar(100),
    external_id     varchar(100)
);

create table markings (
    id                  integer         primary key generated by default as identity,
    point_id            integer         references points(id),
    number              varchar(100),
    type                varchar(100)
);

create table service (
    id                  integer         primary key generated by default as identity,
    point_id            integer         references points(id),
    user_id             integer[],
    appointment_date    timestamp,
    execution_date      timestamp,
    comment             varchar(500),
    status              varchar(100),
    sent                boolean,
    sent_by             integer,
    without_task        boolean           
);

create table service_works (
    id              integer         primary key generated by default as identity,
    service_id      integer         references service(id),
    type            varchar(20),
    work            varchar(100),
    arc             integer
);

-- service_works type required, done

create table media (
    id              integer         primary key generated by default as identity,
    service_id      integer         references service(id),
    media_type      varchar(20),
    media_name      varchar(100)
);

create table tasks (
    id              integer         primary key generated by default as identity,
    point_id        integer         references points(id),
    type            varchar(100),
    comment         varchar(500),
    service_id      integer         references service(id),
    customer        varchar(100),
    entry_date      timestamp,
    deadline        timestamp,
    done            boolean
);